### ISSUE TITLE
Using argparse instead of argv

### ISSUE THREAD

**Issue by MF366-Coding** [MaybeHawk1/To-pee#1]
There is a module that comes built-in into Python and let's you handle arguments via the commandline. It's called `argparse`.

**Comment by MaybeHawk1** [comment]
hell naw this code base is a mess, i aint making it any better 🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏 suggestion was fire tho

**Comment by MF366-Coding** [comment]
LMFAOOO alrighty then np
